spring:
  application:
    name: back
  profiles:
    active: dev
  output:
    ansi:
      enabled: always
  datasource:
    hikari:
      auto-commit: false
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
<<<<<<< Updated upstream
    com.back: DEBUG

jwt:
  secret: "01234567890123456789012345678901"  # 최소 32자(256비트) 이상 (아직 환경변수 처리 하지 않았음)
  access-token-validity: 1800000             # 30분 (밀리초)
  refresh-token-validity: 604800000          # 7일 (밀리초)
=======
    com.back: DEBUG
>>>>>>> Stashed changes
